spring:
  rabbitmq:
    host: 192.168.11.32
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual  # 开启手动Ack
        prefetch: 10
    publisher-confirm-type: correlated  # 新版本
    publisher-returns: true # 开启Return机制
