logging:
    level:
        com:
            baomidou:
                mybatisplus: info
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: com.bobo.mp.domain.pojo
server:
    port: 8081
    tomcat:
        connection-timeout: 100
spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
yunst:
    datasource:
        config:
            driverClassName: oracle.jdbc.OracleDriver
            jdbc-url: jdbc:oracle:thin:@192.168.30.54:1521:orcldb
            password: uat_QAZ123
            username: yunstdb
        report:
            druid:
                driverClassName: oracle.jdbc.driver.OracleDriver
            jdbc-url: jdbc:oracle:thin:@192.168.30.54:1521:orcldb
            maximumPoolSize: 5
            password: uat_QAZ123
            username: yunstdb
