server:
  port: 8080
  shutdown: graceful

# 设置 OkHttp 的日志级别为 DEBUG
logging:
  level:
    okhttp3: DEBUG

log:
  path: /app/saasyunst/logs/base

list:
  users:
    - uid: 0x0001
      nickname: xiaohua
    - uid: 0x002
      nickname: xiaolan

config-list:
  app:
    - url: http://192.168.38.24:8080/
      appId: 21762000921804636162
      secretKey: 878427523d3525e070298d44481b8d2e
      privateKey: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgiaZmB+feACtziE8SYjVZsaQwLNLRiyO8ebSupeoWIF2gCgYIKoEcz1UBgi2hRANCAATwEo0zq6KaB992PToWeJH52LmfS0sFovnB8/LMaoIAOTlFJtA3YgjWXKlO3KT+GqOCfCC4xE60isCr28tqy7hM
      allinpayPublicKey: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEu9LNkJlyLtjJxtQWIGlcZ/hyHt5eZ7LEH1nfOiK1H9HsE1cMPu5KK5jZVTtAyc7lPMXixUMirf6A3tMbuMbgqg==
    - url: http://192.168.38.24:8080/
      appId: 21772171096426889217
      secretKey: 878427523d3525e070298d44481b8d2e
      privateKey: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgiaZmB+feACtziE8SYjVZsaQwLNLRiyO8ebSupeoWIF2gCgYIKoEcz1UBgi2hRANCAATwEo0zq6KaB992PToWeJH52LmfS0sFovnB8/LMaoIAOTlFJtA3YgjWXKlO3KT+GqOCfCC4xE60isCr28tqy7hM
      allinpayPublicKey: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEu9LNkJlyLtjJxtQWIGlcZ/hyHt5eZ7LEH1nfOiK1H9HsE1cMPu5KK5jZVTtAyc7lPMXixUMirf6A3tMbuMbgqg==
    - url: http://192.168.38.24:8080/
      appId: 21777219938337234946
      secretKey: 878427523d3525e070298d44481b8d2e
      privateKey: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgULvkqyQUyaMvmt+pNRbd4pXmMFz6p7EthuotPv4i04ugCgYIKoEcz1UBgi2hRANCAARE00L9Tz3LU8lIfFdMrnefiEb4HXwqc/6+3OmOLCR+EIyLwYrc6OKMkjXDZw1aq0r2CgcY7dy33B8r6yUmzg8D
      allinpayPublicKey: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEu9LNkJlyLtjJxtQWIGlcZ/hyHt5eZ7LEH1nfOiK1H9HsE1cMPu5KK5jZVTtAyc7lPMXixUMirf6A3tMbuMbgqg==
