server:
  port: 8080
  servlet:
    context-path:
  shutdown: graceful

# 设置 OkHttp 的日志级别为 DEBUG
logging:
  level:
    okhttp3: DEBUG

log:
  path: /app/saasyunst/logs/base

list:
  users:
    - uid: 0x0001
      nickname: xiaohua
    - uid: 0x002
      nickname: xiaolan

# 渠道参数
channel:
  yunst2:
    # 测试1
    #  request-url-prefix: http://192.168.38.24:8080/
    #  download-url-prefix: http://192.168.38.24:8080/
    #  upload-url-prefix: http://192.168.38.24:8080/
    # 测试2
    request-url-prefix: http://192.168.93.26:8080/
    download-url-prefix: http://192.168.93.26:8080/
    upload-url-prefix: http://192.168.93.26:8080/
    #  request-url-prefix: https://ibsapi.allinpay.com/
    #  download-url-prefix: https://ibsapi.allinpay.com/
    #  upload-url-prefix: https://ibsapi.allinpay.com/
    download-file-path: /app/smartyunst/downloads/files/
    verifyPublicKey:
      api:
        allinpayPublicKey: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEu9LNkJlyLtjJxtQWIGlcZ/hyHt5eZ7LEH1nfOiK1H9HsE1cMPu5KK5jZVTtAyc7lPMXixUMirf6A3tMbuMbgqg==
      sass:
        allinpayPublicKey: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEu9LNkJlyLtjJxtQWIGlcZ/hyHt5eZ7LEH1nfOiK1H9HsE1cMPu5KK5jZVTtAyc7lPMXixUMirf6A3tMbuMbgqg==
    config-list:
      app:
        - url:
          appId:
          spAppId: 1234567800
          channelType: 1
          merchantTag: 0
          sensitiveEncryptTag: 1
          secretKey: 878427523d3525e070298d44481b8d2e
          privateKey: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgSw1xZjuSVJZuQhXzUsWkojABSh/p4AGEGsrzsbZWVUmgCgYIKoEcz1UBgi2hRANCAARcV29rRwkf/s57G7jOqWxt62OKGtDqan6icmxI2bfstaM6EFHoEhrWXJmea6Y2XCqql/g4FYH1Zkmdd/yN3k9w
          allinpayPublicKey: ${channel.yunst2.verifyPublicKey.sass.allinpayPublicKey}
          urlConfig:
            request-url-prefix: ${channel.yunst2.request-url-prefix}
            download-url-prefix: ${channel.yunst2.download-url-prefix}
            upload-url-prefix: ${channel.yunst2.upload-url-prefix}