# 应用名称
spring:
  application:
    name: msb-webflux-stock
  r2dbc:
    url: r2dbc:mysql://localhost:3306/stock_subscription?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  thymeleaf:
    cache: false
server:
  port: 8888

