logging:
  level:
    com:
      baomidou:
        mybatisplus: info
mybatis-plus:
  # 用p6spy代替
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.bobo.mp.domain.pojo
server:
  port: 8081
  tomcat:
    connection-timeout: 100
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 全局接口配置，使序列化后的 JSON 响应中不包含 null 值的字段或者在类级别上使用 `@JsonInclude(JsonInclude.Include.NON_NULL)` 注解
    default-property-inclusion: non_null
      #db
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      username: appuser
      password: appuser
      #    url: jdbc:mysql://192.168.30.30:12307/smartyunst?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
      #    driver-class-name: com.mysql.cj.jdbc.Driver
      # p6spy在日志中打印完整Mybatis可执行的SQL语句 并记录执行时间 替代mybatis自己的日志输出 p6spy
      url: jdbc:p6spy:mysql://192.168.30.30:12307/smartyunst?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
yunst:
  datasource:
    config:
      driverClassName: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.30.54:1521:orcldb
      password: uat_QAZ123
      username: yunstdb
    report:
      druid:
        driverClassName: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.30.54:1521:orcldb
      maximumPoolSize: 5
      password: uat_QAZ123
      username: yunstdb
